language: node_js

node_js:
  - lts/*

os: linux

dist: xenial

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  yarn: true
  directories:
    - ~/.cache

branches:
  only:
    - main

script:
  - yarn test --ci
  - yarn dev & wait-on http://localhost:3000
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ];
    then
      yarn cy:run --record --key $CY_KEY;
    else
      yarn cy:run;
    fi'
